name = "api-fraser-ever-after"
main = "src/index.ts"
compatibility_date = "2023-12-06"
account_id = "e335da0940211ba812ca4a60fa9277c9"
workers_dev = true
[[d1_databases]]
binding = "DB"
database_name = "FRASER_EVER_AFTER"
database_id = "02a43192-2fde-445b-9714-66034006cccb"